service: authorization-service
frameworkVersion: '3'
plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
  stage: dev
  region: us-east-1
  versionFunctions: true
functions:
  basicAuthorizer:
    handler: src/functions/basicAuthorizer/handler.main
    events:
      - http:
          method: get
          path: /token
          cors: true
    name: authorization-service-dev-basicAuthorizer
package:
  individually: true
custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
      - pg-native
    target: node14
    define: {}
    platform: node
    concurrency: 10
